### PR TITLE
062 migrate to layout

### LINKED ISSUE #62: Migrate To Layout
## Description

At the moment the `<Header />` and `<Footer />` components are duplicated across each page manually (or sometimes even missing). We want to move them to the layout.tsx file while preserving the look of the website.

## Acceptance Criteria

- [ ] Header in layout.tsx
- [ ] Footer in layout.tsx
- [ ] Header & footer not in any page.tsx's
- [ ] Visual layout of the pages is unchanged (or only changed slightly)

## Notes

Tips
- Would recommend setting up a vertical flexbox in layout.tsx!
- Also: it seems some pages have different backgrounds (e.g. /projects) - you'll need to come up with a way to handle this.

Because this ticket affects the entire repo tag me (Nate) as a reviewer so I can make any commits I need to afterwards.

### PR DESCRIPTION
**Pull request by Oculux314**
## Context

We want to have a consistent page layout for each page.

Closes #62 

## What Changed?

- Removed `<Header />` and `<Footer />` components from each individual page
- Added footer and header to `layout.tsx`
- Adjusted `layout.tsx`
  - Now contains `<main />` (which is now a column [flexbox](https://www.joshwcomeau.com/css/interactive-guide-to-flexbox/))
  - Header is now [positioned absolutely](https://www.w3schools.com/css/css_positioning.asp)
  - Footer now stays at the bottom of the page if the page is too small
  - Adjusted pages to look like before*

## How To Review

- Start up the app and check nothing's broken on each of the pages!
- Check out `layout.tsx` and the home page `page.tsx` pages first
- Review code commit-wise

## Notes

*New tailwind styles: `mt-header` and `pt-header`

### CODE REVIEW

**Review by h4yleysh4rpe — COMMENTED** [review]
Looks good to me. I am just wondering whether it would be possible to have the footer moved up slightly on the 404 not found page? (See vid - at the moment you have to scroll to see the footer, which is maybe a bit odd given that the 404 page doesn't really have any content to justify the footer being off the bottom of the page?). I am happy to have a go at this but honestly not sure I'll know how to...


https://github.com/user-attachments/assets/17fc4a8f-182f-4cd7-9d1d-a9e827ddf53c

**Comment by Oculux314** [comment]
> Looks good to me. I am just wondering whether it would be possible to have the footer moved up slightly on the 404 not found page? (See vid - at the moment you have to scroll to see the footer, which is maybe a bit odd given that the 404 page doesn't really have any content to justify the footer being off the bottom of the page?). I am happy to have a go at this but honestly not sure I'll know how to...
> 
>  Recording.2024-08-06.112234.mp4

Ah! Don't worry about that that's just Next's default 404 page (which we can't really change).
We should probably make our own, come to think of it... if you're interested keep an eye out!

**Review by h4yleysh4rpe — APPROVED** [review]
LGTM!

**Review by YvonneLiew — APPROVED** [review]
lgtm

**Pull request merged**
