### PR TITLE
066 strapi default values

### LINKED ISSUE #66: Strapi Default Values
## Description

Create default values in Strapi so that we don't have to go through the painful Strapi setup process every time we clone the repo. Doesn't have to be production-ready descriptions/images, but ideally something nicely that just `dgdfjshkfjsk` y'know :)

## Acceptance Criteria

- [ ] Upon cloning the repo, you don't need to do anything in Strapi except save & publish each page.

### PR DESCRIPTION
**Pull request by eilecn**
Set default strapi values.

Closes #66 

Check that the set strapi values show up when the repo is cloned.

### CODE REVIEW

**Comment by Oculux314** [comment]
Hey @eilecn is this what the page is meant to look like?
image

**Comment by eilecn** [comment]
@Oculux314 Yes!

**Review by Oculux314 — APPROVED** [review]
Lgtm then!!

P.s. feel free to also request reviews from others so everyone gets experience reviewing PRs - recommendation is one of Yvonne and me, + one other :D

**Review by YvonneLiew — APPROVED** [review]
lgtm

**Pull request merged**
